name: Build and Publish image to Docker Hub
on: [workflow_dispatch]

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t thesaurus5689/devops-qrcode-api:latest ./api/

      - name: Push Docker image
        run: docker push thesaurus5689/devops-qrcode-api:latest
